# Generated by Django 5.2 on 2025-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
