# Generated by Django 5.2 on 2025-04-22 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_song_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(75)]),
        ),
    ]
