# Generated by Django 5.2 on 2025-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_song_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
