# Generated by Django 5.2 on 2025-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_alter_song_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
