# Generated by Django 5.2 on 2025-04-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_alter_song_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
    ]
