# Generated by Django 5.2 on 2025-04-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0006_remove_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
