# Generated by Django 5.2 on 2025-05-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0007_playlist_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['name']},
        ),
    ]
