# Generated by Django 5.2 on 2025-04-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('playlists', '0007_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist'),
        ),
    ]
