# Generated by Django 5.2 on 2025-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='called_numbers',
            field=models.JSONField(default=list),
        ),
    ]
